### ISSUE TITLE
how to set nodeActions

### ISSUE THREAD

**Issue by bubifengyun** [kartik-v/yii2-tree-manager#101]
Thanks for your great work.

I find that #91, and code for the same purpose. The left is tree manager, and the right is gridview. in tree manger i do as follows:

```php
// tree manger.php
// add children and itself.
$query = Unit::findOne($unit_id)
    ->children()
    ->orWhere(['id' => $unit_id])
    ->addOrderBy('root, lft');
?>

<?= TreeView::widget([
    'query'             => $query,
    'headingOptions'    => ['label' => 'Unit'],
    'nodeView'          => '@frontend/views/personinfo/_nodegridview',
    'isAdmin'           => false,
    'rootOptions'       => ['label' => 'Units I can see'],
	'displayValue'      => $unit_id,
]) ?>
```

I add my own node view in `@frontend/views/personinfo/_nodegridview` as

```php
// _nodegridview.php
Pjax::begin(['id' => 'kv-'.uniqid(), 'timeout' => false, 'enablePushState' => false, 'clientOptions' => ['method' => 'POST']]);
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        'name',
        'is_married',
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}{update}',
        ],
    ],
]);
Pjax::end();
```

If i click the node in the left tree manger, the right gridview will show the right girdview. but, when i click header of the gridview to sort, it will pop errors:

```
{"name":"Exception","message":"The operation is not allowed.","code":0,"type":"yii\\base\\InvalidCallException","file":"/opt/lampp/htdocs/www/wuzhishan/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php","line":73,"stack-trace":["#0 /opt/lampp/htdocs/www/wuzhishan/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php(159): kartik\\tree\\controllers\\NodeController::checkValidRequest()","#1 [internal function]: kartik\\tree\\controllers\\NodeController->actionManage()","#2 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)","#3 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array)","#6 /opt/lampp/htdocs/www/wuzhishan/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 /opt/lampp/htdocs/www/wuzhishan/frontend/web/index.php(18): yii\\base\\Application->run()","#8 {main}"]}
```

I think it may be the reason of `kartik\\tree\\controllers\\NodeController->actionManage()`.
So I want to override the function actionManage, but it will wait forever and never go into my actionManage. my config in TreeView as follows:

```php
<?= TreeView::widget([
    'query'             => $query,
    'headingOptions'    => ['label' => 'Unit'],
    'nodeView'          => '@frontend/views/personinfo/_nodegridview',
    'nodeActions' => [
        Module::NODE_MANAGE => Url::to(['@frontend/personinfo/manage']),
    ],
    'isAdmin'           => false,
    'rootOptions'       => ['label' => 'Units I can see'],
	'displayValue'      => $unit_id,
]) ?>
```
There's something wrong in `Module::NODE_MANAGE => Url::to(['@frontend/personinfo/manage']),`. But i cannot find demo or any help. Could you help me? Thank you.

**Comment by bubifengyun** [comment]
Thank you, I have solved this problem by another way. I will record my method, then paste here.

**Comment by lowap** [comment]
how did you solve it?

**Comment by bubifengyun** [comment]
sorry for my bad english. I write in chinese, total code is here.

- https://github.com/bubifengyun/code-book-yii2-dev-process/blob/master/frontend/controllers/PersoninfoController.php
- https://my.oschina.net/bubifengyun/blog/605908
- https://my.oschina.net/bubifengyun/blog/776979

if you dont know chinese, you can translate to english
