### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Unsupported operand types'

### ISSUE THREAD

**Issue by Serega67** [kartik-v/yii2-tree-manager#133]
Hello!
I get this error when I try to execute **console** command (**console\yii product\test ...**). Action Test is very simple:
```
public function actionTest($id)
{
        $product = \backend\modules\products\models\Product::findOne($id);        
}
```

Model Product extends \kartik\tree\models\Tree.
In init() function of this model I attach some event handlers (I added line numbers to this piece of model code for watch some error from stack trace):
```
114: public function init()
115: {
116:        $this->_productSystem = new ProductSystem([
117:            'scenario' => $this->scenario
118:        ]);
119:        
120:        $this->on(self::EVENT_NEW_PRODUCT_SYSTEM, [$this, 'onNewProductSystem']);
121:        $this->on(self::EVENT_AFTER_FIND_PRODUCT, [$this, 'onAfterFindProduct']);
122:        $this->on(self::EVENT_ADD_SETTING_PRODUCT, [$this, 'onAddSettingsProduct']);
123:        
124:        parent::init();        
125:}
```

Full stack trace of error:
```
PHP Fatal Error 'yii\base\ErrorException' with message 'Unsupported operand types'          
                                                                                            
in C:\OpenServer\domains\domau\vendor\kartik-v\yii2-tree-manager\models\TreeTrait.php:86    
                                                                                            
Stack trace:                                                                                
#0 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Component.php(646): backend\modules\
products\models\Product->behaviors()                                                        
#1 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Component.php(479): yii\base\Compone
nt->ensureBehaviors()                                                                       
#2 C:\OpenServer\domains\domau\backend\modules\products\models\Product.php(120): yii\base\Co
mponent->on()                                                                               
#3 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Object.php(107): backend\modules\pro
ducts\models\Product->init()                                                                
#4 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\ActiveQuery.php(432): yii\base\Object-
>__construct()                                                                              
#5 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\ActiveQuery.php(146): yii\db\ActiveQue
ry->buildJoinWith()                                                                         
#6 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\QueryBuilder.php(89): yii\db\ActiveQue
ry->prepare()                                                                               
#7 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\ActiveQuery.php(314): yii\db\QueryBuil
der->build()                                                                                
#8 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\Query.php(247): yii\db\ActiveQuery->cr
eateCommand()                                                                               
#9 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\ActiveQuery.php(290): yii\db\Query->on
e()                                                                                         
#10 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\db\BaseActiveRecord.php(102): yii\db\Act
iveQuery->one()                                                                             
#11 C:\OpenServer\domains\domau\console\controllers\ProductController.php(85): yii\db\BaseAc
tiveRecord::findOne()                                                                       
#12 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\InlineAction.php(55): console\contr
ollers\ProductController->actionTest()                                                      
#13 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_f
unc_array:{C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\InlineAction.php:55}()      
#14 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\Inlin
eAction->runWithParams()                                                                    
#15 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\console\Controller.php(108): yii\base\Co
ntroller->runAction()                                                                       
#16 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Contro
ller->runAction()                                                                           
#17 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\console\Application.php(167): yii\base\M
odule->runAction()                                                                          
#18 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\console\Application.php(143): yii\consol
e\Application->runAction()                                                                  
#19 C:\OpenServer\domains\domau\vendor\yiisoft\yii2\base\Application.php(375): yii\console\A
pplication->handleRequest()                                                                 
#20 C:\OpenServer\domains\domau\console\yii(26): yii\base\Application->run()                
#21 {main}                                               
```                                   

If I comment lines on the Init() method:
```
$this->on(self::EVENT_NEW_PRODUCT_SYSTEM, [$this, 'onNewProductSystem']);
$this->on(self::EVENT_AFTER_FIND_PRODUCT, [$this, 'onAfterFindProduct']);
$this->on(self::EVENT_ADD_SETTING_PRODUCT, [$this, 'onAddSettingsProduct']);
```
then PHP worried about call the next line:
`
$this->trigger(self::EVENT_AFTER_FIND_PRODUCT, $event);
`
and so on.

**In the frontend and backend web application this model work fine.**

Versions:
Yii2: 2.0.7
kartik-v/yii2-tree-manager  -  v1.0.5
creocoder/yii2-nested-sets -  0.9.0

Please, help me fix this error.

**Comment by kartik-v** [comment]
Please [read the extension docs](http://demos.krajee.com/tree-manager). You must ensure the module `treemanager` must be defined also in your console application config.

**Comment by Serega67** [comment]
Thank you very much! 
You advice helped me. :)
