### ISSUE TITLE
Documentation limitation 

### ISSUE THREAD

**Issue by saidbakr** [kartik-v/yii2-tree-manager#62]
The documenation, well, show how to use master page for the tree. i.e using it from the index action. However, some users for the plugin may be got lost when they want to use it to create new node.

I think that documentation should cover this aspect in more details.

**Comment by kartik-v** [comment]
It involves clicking toolbar buttons to create nodes. You can read the getting started section and [Step 4: Using TreeView Widget](http://demos.krajee.com/tree-manager#using-treeview) and refer end part of the step 4.

**Comment by saidbakr** [comment]
Does it need a table with initial data? I have an empty table and the only active button is Add New Root, and It does not add anything with no any error message.

**Comment by kartik-v** [comment]
No it need not have a table with initial data. You need to start with `root` node creation.

Just ensure you have the latest code from `dev-master` - there are some updates to `root` node creation. This release will be tagged for auto-update later.

Let know once you tested with code from `dev-master` if you are facing issues.

**Comment by saidbakr** [comment]
I installed it using the composer command regarded in the documentation:

```
 composer require kartik-v/yii2-tree-manager "@dev"
```
It seems, from browser's console that the URL ` http://localhost/inventory/backend/web/index.php?r=treemanager%2Fnode%2Fmanage&kvtree=-385354956` causes internal server error. The following is output of the page:

```
{"name":"Exception","message":"This operation is not allowed.","code":0,"type":"yii\\base\\InvalidCallException","file":"C:\\xampp-2\\htdocs\\inventory\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php","line":66,"stack-trace":["#0 C:\\xampp-2\\htdocs\\inventory\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php(143): kartik\\tree\\controllers\\NodeController::checkValidRequest()","#1 [internal function]: kartik\\tree\\controllers\\NodeController->actionManage()","#2 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(55): call_user_func_array(Array, Array)","#3 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\web\\Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array)","#6 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 C:\\xampp-2\\htdocs\\inventory\\backend\\web\\index.php(18): yii\\base\\Application->run()","#8 {main}"]}
``` 
The LOADING indicator still works forever.

**Comment by saidbakr** [comment]
Finally I have got it works, I just have to use the first method of creating model -without trait-. Now I will try to show other fields in widget such as description. Thank you.

**Comment by bubifengyun** [comment]
@saidbakr hi,saidbakr, I have the same problem with you.

```php
{"name":"Exception","message":"This operation is not allowed.","code":0,"type":"yii\\base\\InvalidCallException","file":"C:\\xampp-2\\htdocs\\inventory\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php","line":66,"stack-trace":["#0 C:\\xampp-2\\htdocs\\inventory\\vendor\\kartik-v\\yii2-tree-manager\\controllers\\NodeController.php(143): kartik\\tree\\controllers\\NodeController::checkValidRequest()","#1 [internal function]: kartik\\tree\\controllers\\NodeController->actionManage()","#2 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(55): call_user_func_array(Array, Array)","#3 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)","#4 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Module.php(455): yii\\base\\Controller->runAction('manage', Array)","#5 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\web\\Application.php(84): yii\\base\\Module->runAction('treemanager/nod...', Array)","#6 C:\\xampp-2\\htdocs\\inventory\\vendor\\yiisoft\\yii2\\base\\Application.php(375): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#7 C:\\xampp-2\\htdocs\\inventory\\backend\\web\\index.php(18): yii\\base\\Application->run()","#8 {main}"]}
```
Could you give some more detail about how to solve this problem? Thank you.
